### PR TITLE
Add speedIndex probe and metric

### PR DESCRIPTION
**Pull request by andrewrota**
Adds probe and metric for RUM SpeedIndex, an indexed value representing the average time at which visible parts of the page are displayed) from resource timings.

Related issue: #69

### CODE REVIEW

**Comment by andrewrota** [comment]
I'm going to refactor this to pull in the rum-speedindex package as a dependency

**Comment by axemclion** [comment]
@andrewrota Sorry for not having responded sooner - I think making it a separate package would be better. That way, browser-perf and other tools just supply the information, and hte actual number can be calculated in a more common way.

**Comment by andrewrota** [comment]
@axemclion Do you mean pulling in rum-speedIndex as a dependency (like this https://github.com/axemclion/browser-perf/compare/master...andrewrota:57bd61b985372d895763db85d5b3a5f36aa91349) or packaging the entire speed index metric separately as a custom metric + probe?

**Comment by axemclion** [comment]
@andrewrota Sorry for a late response, had been busy with some conferences. 

Pulling the metric + probe may not be as useful, and others cannot include that module anyway - it is too browser-perf specific. 

I meant more like the rum-speedindex part. The [RUM-SpeedIndex](https://github.com/WPO-Foundation/RUM-SpeedIndex#a6d4e1e1db56a10ab514493f70970e06f283da16) was what I was talking about - that is great.

**Comment by axemclion** [comment]
@andrewrota Hey, did you need any other info on the PR ?

**Comment by andrewrota** [comment]
@axemclion Sorry, wasn't sure what your last suggestion was.  This [patch](https://github.com/axemclion/browser-perf/compare/master...andrewrota:57bd61b985372d895763db85d5b3a5f36aa91349) is still what I'm thinking: pull in rum-speedindex as a module from npm and inject it into the page with a probe, then use a metric to record the data.

**Pull request closed without merging**
